### ISSUE TITLE
tableRule 配置问题

### ISSUE THREAD

**Issue by yuangang19880212** [PomeloFoundation/Entity-Framework-Core-MyCat-Proxy#2]
仔细查看了这个代理的代码，是有问题的，在demo中，只有一个 实体类也就只有一个 主键，所以不会产生问题
![e14](https://cloud.githubusercontent.com/assets/19831723/18158344/516fecb8-7055-11e6-83a5-c4d4d3f46e61.png)

通过遍历 schema.xml里的 primaryKey 组合 拆分的列名称 增加 rule.xml的 tableRule

比如：我有个四个实体类，他们的主键分别是ID，ID，ID,UserID，那么生成的 tableRule 的 columns就会是
<tableRule name="XXX">
        <rule>
            <columns>ID,ID,ID,UserID</columns>
            <algorithm>XXX</algorithm>
        </rule>
    </tableRule>

但是这样是错误的，columns 只能指定一个，如果按照上述，那么MyCat启动就会出错：
因为rule columns出现多个值
![e15](https://cloud.githubusercontent.com/assets/19831723/18158569/b120c762-7056-11e6-831e-45191b10c794.png)

手动修改 colums 只保留一个 就可以正常运行
多个是不行的，官方文档也是只支持单列，所以我们要修改代理程序，对于不同的primaryKey 配置多个tableRule

**Comment by yukozh** [comment]
请使用alpha2版本的代理程序
